/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2017-05-26 03:12:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("  <title>自己仿照login写的登录页面</title>\r\n");
      out.write("  <style media=\"screen\">\r\n");
      out.write("    * {\r\n");
      out.write("      padding: 0px;\r\n");
      out.write("      margin: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: rgb(74,55,74);\r\n");
      out.write("    }\r\n");
      out.write("    #form {\r\n");
      out.write("      width: 300px;\r\n");
      out.write("      height: 300px;\r\n");
      out.write("      margin: -150px 0 0 -150px;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 50%;\r\n");
      out.write("      left: 50%;\r\n");
      out.write("    }\r\n");
      out.write("    h1 {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      color: rgb(255,255,255);\r\n");
      out.write("      text-shadow: rgb(255,255,255) 0px 0px 10px;\r\n");
      out.write("    }\r\n");
      out.write("    input {\r\n");
      out.write("      border: 1px;\r\n");
      out.write("      height: 40px;\r\n");
      out.write("      width: 280px;\r\n");
      out.write("      margin-top: 10px;\r\n");
      out.write("      background-color: #2D2D3F;\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding-left: 20px;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("    button {\r\n");
      out.write("      border: 1px;\r\n");
      out.write("      height: 40px;\r\n");
      out.write("      width: 300px;\r\n");
      out.write("      margin-top: 10px;\r\n");
      out.write("      background-color: rgb(74,119,212);\r\n");
      out.write("      color: white;\r\n");
      out.write("      letter-spacing: 1.5em;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      display: block;\r\n");
      out.write("    }\r\n");
      out.write("    button:hover {\r\n");
      out.write("      background-color: rgb(14, 142, 207);\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div id=\"form\">\r\n");
      out.write("    <form action=\"loginAction.jsp\" method=\"post\">\r\n");
      out.write("      <h1>Login</h1>\r\n");
      out.write("      <input type=\"text\" placeholder=\"用户名\"  name=\"u\" required>\r\n");
      out.write("      <input type=\"password\" placeholder=\"密码\" name=\"p\" required>\r\n");
      out.write("      <button>登录</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
