/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2017-05-21 04:44:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

      Class.forName("com.mysql.jdbc.Driver");
      String url = "jdbc:mysql://localhost:3306/s59";
      String user = "root";
      String password = "1018222wxw";
      Connection conn = DriverManager.getConnection(url,  user,password);
      String sql = "SELECT e.eId,e.eName,d.dName,e.eSex,e.eBorn,e.elove from dep d , emp e where e.dId = d.dId";
      PreparedStatement ps = conn.prepareStatement(sql);
      ResultSet rs = ps.executeQuery();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=\"1px\" align=\"center\" width=\"60%\">\r\n");
      out.write("  <thead align=\"center\">\r\n");
      out.write("    <th>员工编号</th>\r\n");
      out.write("    <th>员工姓名</th>\r\n");
      out.write("    <th>所在部门</th>\r\n");
      out.write("    <th>员工性别</th>\r\n");
      out.write("    <th>出生日期</th>\r\n");
      out.write("    <th>爱好</th>\r\n");
      out.write("    <th>操作</th>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody align=\"center\">\r\n");
      out.write("    ");
 while(rs.next()){ 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>");
      out.print( rs.getInt(1));
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( rs.getString(2));
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( rs.getString(3));
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( rs.getString(4));
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( rs.getString(5));
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( rs.getString(6));
      out.write("</td>\r\n");
      out.write("        <td>\r\n");
      out.write("            <a href=\"update.jsp?eId=");
      out.print(rs.getInt(1));
      out.write("\">修改</a>    |\r\n");
      out.write("            <a href=\"delete.jsp?eId=");
      out.print(rs.getInt(1));
      out.write("\">删除</a>\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<center><h2><a href=\"register.jsp\">新增员工</a></h2></center>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
