/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2017-05-21 04:51:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

      Class.forName("com.mysql.jdbc.Driver");
      String url = "jdbc:mysql://localhost:3306/s59";
      String user = "root";
      String pass = "1018222wxw";

      Connection conn = DriverManager.getConnection(url, user, pass);
      String sql = "SELECT dId, dName from dep";
      PreparedStatement ps = conn.prepareStatement(sql);
      ResultSet rs = ps.executeQuery();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"updateAction.jsp?eId=");
      out.print(request.getParameter("eId"));
      out.write("\" method=\"post\">\r\n");
      out.write("  姓名： <input type=\"text\" name=\"username\" >\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  所在部门：\r\n");
      out.write("  <select  name=\"dep\">\r\n");
      out.write("    ");
 while(rs.next()){ 
      out.write("\r\n");
      out.write("       <option value=\"");
      out.print(rs.getInt(1));
      out.write("\">\r\n");
      out.write("        ");
      out.print(rs.getString(2));
      out.write("\r\n");
      out.write("       </option>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("  </select>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  性别：\r\n");
      out.write("      <input type=\"radio\" name=\"sex\" value=\"男\">男\r\n");
      out.write("      <input type=\"radio\" name=\"sex\" value=\"女\">女\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  出生日期：\r\n");
      out.write("  <input type=\"date\" name=\"birth\">\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  爱好：\r\n");
      out.write("  <input type=\"checkbox\" name=\"hobby\" value=\"吃\">吃\r\n");
      out.write("  <input type=\"checkbox\" name=\"hobby\" value=\"喝\">喝\r\n");
      out.write("  <input type=\"checkbox\" name=\"hobby\" value=\"玩\">玩\r\n");
      out.write("  <input type=\"checkbox\" name=\"hobby\" value=\"乐\">乐\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <input type=\"submit\" name=\"\" value=\"修改\">\r\n");
      out.write("  <input type=\"reset\" name=\"\" value=\"重置\">\r\n");
      out.write("</form>\r\n");
 conn.close(); 
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
